import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Alex Balieiro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/portfolio.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Alex Balieiro</h1>
        <h2 className={styles.subtitle}>Developer Frontend</h2>
        <p className={styles.description}>Everything starts here</p>
      </main>

      <footer className={styles.footer}>
        Powered by <span className={styles.logo}>Alex Balieiro</span>
      </footer>
    </div>
  );
}
